image: gitpod/workspace-full
tasks:
  - init: npm install
    command: echo "ZM_RTS_CLIENT=$ZOOM_RTS_CLIENT"
             echo "ZM_RTS_SECRET=$ZOOM_RTS_SECRET"
ports:
  - port: 8080
    onOpen: open-browser
